### ISSUE TITLE
FUIFirestoreTableViewDataSource.h missing in current pod

### ISSUE THREAD

**Issue by ghowen** [firebase/FirebaseUI-iOS#355]
I got curious when Xcode did not recognize the FUIFirestoreTableViewDataSource type. Also code completion did not know this class.

Looking at the Pod in Xcode it seems that the header file for FUIFirestoreTableViewDataSource is missing:

![image](https://user-images.githubusercontent.com/390784/31725939-7ec4cbc2-b41d-11e7-8261-fbda2fbe6668.png)

**Comment by morganchen12** [comment]
Fixed in FirebaseUI v4.5.0. 

Thanks for flagging!

**Comment by ghowen** [comment]
Thanks. The header file now shows, but there still seems to be a problem with the pod:
![image](https://user-images.githubusercontent.com/390784/31739012-5c68a96e-b444-11e7-8160-d7df6d24e20d.png)

**Comment by morganchen12** [comment]
Hmm, can you try clearing your Xcode/Cocoapods caches? The type seems to be correctly defined in the header file and there's nothing special that would prevent it from being recognized.

```
rm -rf ~/Library/Developer/Xcode/DerivedData
pod cache clean FirebaseUI --all
```

**Comment by ghowen** [comment]
I tried both (as well cleaning project & build folder via Xcode) but the problem persists. Here is what Xcode can see with the FUI prefix:

![image](https://user-images.githubusercontent.com/390784/31740941-bac6e114-b44a-11e7-966e-aed719929223.png)

Any idea what this could be? Using Xcode 9 with a Swift 4 project.

**Comment by morganchen12** [comment]
Turns out I left out one of the headers in the umbrella header. This is fixed in the current release, but you'll have to clean pods cache again to re-download the binary from GitHub.

FirestoreUI needs a sample and a set of integration tests like the other issues to prevent stuff like this from happening; I'll file a new issue for that.

**Comment by ghowen** [comment]
Got it. It's working now. Thanks!
