### ISSUE TITLE
OTP not fill in PhoneAuth

### ISSUE THREAD

**Issue by naveengoyal1993** [firebase/FirebaseUI-iOS#775]
I am using the FirebaseUI for Phone Auth. OTP message does not fill the keyboard autofill suggestion box. OTP Code fill view (FUICodeField) does not appear the suggestion box in a keyboard. I have shared the screenshot link for this issue.
![firebase-auth](https://user-images.githubusercontent.com/32010174/65310443-f2beec80-dbab-11e9-8c40-54cb3bdc938e.PNG)

Please help me to resolve this issue.

Env:
Lib: Firebase (v6.8.1), FirebaseAuth (v6.2.3), FirebaseCore (v6.2.3) and FirebaseUI (v8.1.0). 
Deployment Target set to iOS 12.3.
iPhone 6 (v12.4.1).

_Originally posted by @naveengoyal1993 in https://github.com/firebase/FirebaseUI-iOS/issues/515#issuecomment-533486382_

**Comment by artmatsak** [comment]
@morganchen12 That doesn't work for me either, any suggestions please? Deployment target is iOS 12.1.

![IMG-0597](https://user-images.githubusercontent.com/5328078/67268227-3c08a180-f4b4-11e9-9256-fd0848e800e9.jpg)

**Comment by alex-vasenin** [comment]
Doesn't work for me either (iOS 13), despite `FUICodeField` implements proper `textContentType`

**Comment by ninja342** [comment]
Same issue

**Comment by sfoulston** [comment]
Experiencing the same issue here

**Comment by vmkcom** [comment]
Same issue for me

**Comment by qubblr** [comment]
Same issue here

**Comment by alex-vasenin** [comment]
Any updates on this?

**Comment by nikitaame** [comment]
Would love to see this resolved to better our user's sign-in and sign-up process :)

**Comment by WestyHopkins** [comment]
It would be incredible if you could please fix this - it's a small thing but it makes sign-up much more seamless for our users. Thanks!

**Comment by dtran320** [comment]
👍 on this. Likely going to have to implement our own signup screen instead of using the authUI phoneNumber one until this is resolved.

**Comment by dtran320** [comment]
Hmm, I'm confused— https://github.com/firebase/FirebaseUI-iOS/pull/516/files#r217218746 looks like it would fix this, but I don't see that code in `FUICodeField.m`

**Comment by morganchen12** [comment]
Hey @dtran320, I've been meaning to take care of it for a while but haven't found the time. I'm happy to review a PR, otherwise I will try to get to it soon.

Sorry for the delay everyone.

**Comment by morganchen12** [comment]
This fix has been released.

**Comment by naveengoyal1993** [comment]
Still, this fix is not working for me.
Env:
Lib: FirebaseAuth (v6.18.0), FirebaseCore (v6.6.3) and FirebaseUI (v8.4.2).
Xcode Version: 11.3.1
iPhone 6 (v12.4.5).

**Comment by dtran320** [comment]
OTP doesn't appear for me either using FirebaseAuth (v6.18.0), FirebaseCore (v6.6.3) and FirebaseUI (v8.4.2) as well with iPhone 11 Pro (iOS 13). Funnily enough, it does appear when entering your phone number.

![firebaseauth_otp](https://user-images.githubusercontent.com/177059/75909150-5d817e80-5e00-11ea-8702-eec22a739e5b.jpg)
![firebaseauth](https://user-images.githubusercontent.com/177059/75909152-5e1a1500-5e00-11ea-9230-918cd7fedf1f.jpg)

**Comment by morganchen12** [comment]
Hey all, after testing this again, I'm unable to figure out why the one time passcode is presented on the phone number entry screen but not the code entry screen. When profiling the code, the method fetching the traits from the code entry view isn't called until it's presented, but it's somehow having an effect on the screen before it.

I'll continue to try to debug this and if I don't reach a conclusion I'll file some feedback to Apple.

**Comment by isupremedyou** [comment]
@morganchen12 I have also had it where the phone number entry screen suggests a one time code for the number field before the code entry screen is presented at all. I’ll see if I can’t figure this out and submit a PR later today.

**Comment by willbattel** [comment]
I'm sure this isn't news to you since we're using the same version as everyone else here, but just for the record, we've just implemented PhoneAuth in our app and are experiencing this same thing. The OTP does not appear as an auto-fill suggestion until after starting the auth process a second time, where it appears when entering the phone number.

Let us know if there is anything specific we can do to help diagnose the problem. Thanks!

**Comment by isupremedyou** [comment]
@morganchen12
https://developer.apple.com/documentation/security/password_autofill/enabling_password_autofill_on_a_text_input_view?language=objc

> Warning
> If you use a custom input view for a security code input text field, iOS cannot display the necessary AutoFill UI.

The project will need to be updated to use a `UITextField` for the code entry. It should be possible to accomplish a similar visual appearance, but more importantly the UX of autofill will greatly increase the usefulness of the iOS PhoneAuth.

I've use the Android counterpart for PhoneAuth and the experience is great. I'm a Swift dev, but I can give this a go...but if anyone is more experienced with Objective-C and can get to it quicker, please do. We need to change `FUICodeField` to be a subclass of `UITextField`

**Comment by morganchen12** [comment]
Good catch @isupremedyou, thanks for submitting a fix. I'll take a look at it today.

**Comment by marc-beudet** [comment]
So, is this fixed?

**Comment by gonencmete** [comment]
I'm still having this issue. Both phone number and OTP autofills are not working.

**Comment by liambolling** [comment]
This is still not fixed, please reopen

**Comment by nikitaame** [comment]
A fix for this coming?

**Comment by JustinRohweller** [comment]
I believe it's possible the issue is because the code is always before the word code, and supposedly the requirements from Apple are to have the code come AFTER the word "code".
As in, the template has the code as the first thing the user sees, but Apple wants it after the word "code":
[https://github.com/facebook/react-native/issues/22578#issuecomment-510403610](url)

**Comment by yuchenshi** [comment]
I've filed a bug (b/170673572) internally to track this.

**Comment by barGenda** [comment]
Something new with this feature request?

**Comment by willbattel** [comment]
Yeah, I hate to be a bother but, this is an annoyance that I expected to be solved by now. This issue is over a year old and, while I know the Firebase team has _a lot_ on their plate, this has become a pain point we cannot ignore.

I have a lot of faith in the Firebasers, and we want to continue using FirebaseUI because it does simplify things for us as designed. At your earliest convenience, can we please get more attention towards resolving this issue?

**Comment by isupremedyou** [comment]
Anyone wanting this fixed should take a look at this PR and figure out what's missing. I don't have time to get back to this, but it looks like progress was made by others.

https://github.com/firebase/FirebaseUI-iOS/pull/852#issuecomment-641687963

**Comment by morganchen12** [comment]
This is fixed in the latest version of FirebaseUI. Thanks to @akivab and @isupremedyou for your contributions!

Please let me know if this bug regresses and I'll reopen the issue.

**Comment by nconfrey** [comment]
NOTE: If you are still having this issue, check your `Podfile`: I was following the official README instructions, which pegged the version to 8.0. Update your podfile (or use swift package manager pointing to the master branch of this repo), and you'll pull in the fix.
